"""add conversation status

Revision ID: 4186cd075862
Revises: faddeeaa792e
Create Date: 2026-08-23 18:53:04.848516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4186cd075862'
down_revision: Union[str, None] = 'faddeeaa792e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('collection_384_1222_vector_idx', table_name='collection_384_1222', postgresql_using='hnsw')
    op.drop_table('collection_384_1222')
    op.add_column('conversations', sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='conversationstatusenum'), nullable=False))
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('conversations', 'status')
    op.create_table('collection_384_1222',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['datachunks.chunk_id'], name='collection_384_1222_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_1222_pkey')
    )
    op.create_index('collection_384_1222_vector_idx', 'collection_384_1222', ['vector'], unique=False, postgresql_using='hnsw')
    # ### end Alembic commands ###
