"""add conversation tables

Revision ID: faddeeaa792e
Revises: 2e076c46f2e7
Create Date: 2026-08-23 03:24:24.526122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faddeeaa792e'
down_revision: Union[str, None] = '2e076c46f2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conversation_project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('conversation_id'),
    sa.UniqueConstraint('conversation_uuid')
    )
    op.drop_table('collection_384_124')
    op.drop_index('collection_384_125_vector_idx', table_name='collection_384_125', postgresql_using='hnsw')
    op.drop_table('collection_384_125')
    op.drop_table('collection_384_69')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_384_69',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['datachunks.chunk_id'], name='collection_384_69_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_69_pkey')
    )
    op.create_table('collection_384_125',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['datachunks.chunk_id'], name='collection_384_125_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_125_pkey')
    )
    op.create_index('collection_384_125_vector_idx', 'collection_384_125', ['vector'], unique=False, postgresql_using='hnsw')
    op.create_table('collection_384_124',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['datachunks.chunk_id'], name='collection_384_124_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_384_124_pkey')
    )
    op.drop_table('conversations')
    # ### end Alembic commands ###
